# vim: ts=2 sw=2 et ft=toml

[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome5"


[[block]]
block = "disk_space"
path = "/"
format = "$icon $free"
info_type = "available"
interval = 20

#[[block]]
#block = "net"
#device = "eth0"
#format = "$icon $ip"
#interval = 1
#missing_format = ""


[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency { $boost|} "

[[block]]
block = "memory"
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"

[[block]]
block = "temperature"
interval = 10
format = " $icon "
format_alt = " min: $min C, max: $max C, avg: $average C "
chip = "*-isa-*"

[[block]]
block = "sound"
format = " $icon { $volume|}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

#[[block]]
#block = "backlight"
#device = "intel_backlight"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %d.%m.%y %H:%M:%S') "
timezone = "Europe/Moscow"
interval = 1

