#!/bin/sh

# Quickly removes the directory with large number of files
# Taken from https://unix.stackexchange.com/questions/37329/efficiently-delete-large-directory-containing-thousands-of-files

mkdir empty_dir
rsync -a --delete empty_dir/ $1
rm -r empty_dir
