#!/usr/bin/env bash

# Define source and destination directories
src="$1"
dest="$2"
while inotifywait -r -e modify,create,delete,move $src; do
    # delete after will also replicates delete in src folder
    rsync -avz $src $dest # --delete-after
done
