#!/bin/zsh

# Jump to directory, select file with fzf and open it in default application

eval "$(zoxide init zsh)"  

z "$1" 

local output
output=$(fzf --height 40% --reverse </dev/tty) 
xdg-open "$output"


