#!/bin/bash

# Current WM can be checked with
# wmctrl -m

# xss-lock -- i3lock -n -c 000000 &
i3lock -c 000000 &

sleep 15
[[ $(pgrep i3lock | wc -l) -ne 0 ]] && systemctl suspend
# xset dpms force off
