#!/usr/bin/env python
# Returns a string in which the sequences with percent (%) signs followed by
# two hex digits have been replaced with literal characters.


from urllib.parse import quote
from sys import argv

print(quote(argv[1]))

