#!/usr/bin/env bash

docker run -it --rm \
  -e IGNORE_RUN_AS_ROOT=1 \
  -e LIBVIRT_DEFAULT_URI \
  -v $HOME/.ssh:/home/vagrant/.ssh \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w "${PWD}" \
  --network host \
  docker.io/vagrantlibvirt/vagrant-libvirt:latest \
  vagrant $@
